### PR TITLE
fix: webhook verification using a constant-time comparison

### LINKED ISSUE #1: Implement signature verification
The requests from GitHub are currently not verified using the signature, because [the code is currently using Node's crypto package](https://github.com/octokit/webhooks.js/blob/0e03e470034ac769a28ed37acb524b94e304bf96/src/sign/index.ts#L1). This will be resolved once I create a universal webhook verification package, similar to [`universal-github-app-jwt`](https://github.com/gr2m/universal-github-app-jwt/#readme). For the time being, you could define a secret path that that webhook requests by GitHub are sent to, in order to prevent anyone who knows your workers URL from sending fake webhook requests.

### PR DESCRIPTION
**Pull request by AlCalzone**
I've found that splitting the private key into 3 parts is no longer necessary.

Also the `wrangler` CLI is now available under the `wrangler` package, and the deploy action has a new version. Both simplify the `wrangler.toml` a bit.

I've also taken the liberty to convert the worker.js to the new [module workers](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/) format.

Also, this implements webhook verification using a constant-time comparison
fixes: #1

### CODE REVIEW

File: worker.js [hunk 1]
```diff
@@ -1,97 +1,102 @@
...
+    const payload = JSON.parse(payloadString);
 
-  try {
-    // TODO: implement signature verification
-    // https://github.com/gr2m/cloudflare-worker-github-app-example/issues/1
-    await app.webhooks.receive({
-      id,
-      name,
-      payload,
-    });
```
Comment (gr2m) [inline worker.js:84]: there is now a [`.webhooks.verifyAndReceive()`](https://github.com/octokit/webhooks.js/#webhooksverifyandreceive) method, I'd prefer to use that. Any objections?

**Review by gr2m — COMMENTED** [review]
This is great, thank you so much!

File: worker.js (hunk 1 above)
Comment (AlCalzone) [reply worker.js:84]: There is, but it uses Node's `crypto` module internally which isn't available on Cloudflare, not even with `node_compat = true`. At least I was getting errors when attempting that first.

Comment (gr2m) [reply worker.js:84]: oh I see, thank you! 

Once we move @octokit to ESM, I hope to use conditional exports in https://github.com/octokit/webhooks-methods.js, so that Node / Deno / etc can use native implementations if present. Until then, we can use your method

**Comment by gr2m** [comment]
Any guidance on how to resolve this deploy error?

[image](https://github.com/gr2m/cloudflare-worker-github-app-example/runs/8215770714?check_suite_focus=true#step:4:19)

**Comment by AlCalzone** [comment]
oh yeah, just do what the error says. Add
```
compatibility_date = "<today in yyyy-mm-dd>"
```
to wrangler.toml like [here](https://github.com/zwave-js/firmware-updates/blob/d29c2005df308f490c83d788cabed8264e45daae/wrangler.toml#L4)

**Comment by AlCalzone** [comment]
This just enables all possibly breaking changes before that date that are listed on https://developers.cloudflare.com/workers/platform/compatibility-dates/.

**Comment by gr2m** [comment]
LOoks like we are back in business, thank you!

The `node_compat = true` config is a temporary workaround until we complete ESM transition and we get conditional exports: https://github.com/gr2m/cloudflare-worker-github-app-example/runs/8218002793?check_suite_focus=true#step:6:18
